import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-[#010313]">
          <div className="bg-[#201235]">
            <Navbar></Navbar>
          </div>
          <main className=" place-items-center place-content-center">
            {children}
          </main>

          <footer className=" ">
            <Footer></Footer>
          </footer>
        </div>
      </body>
    </html>
  );
}
